import Head from "next/head";
import { AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import deved from "../public/dev-ed-wave.png";
import Image from "next/image";
import web1 from "../public/web1.png";
import web2 from "../public/web2.png";
import web3 from "../public/web3.png";
import Link from "next/link";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Kevin Moreira | Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Kevin Moreira</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <div className="mx-auto bg-gradient-to-b from-red-500 rounded-full  h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>

            <h2 className="text-5xl py-2 text-red-600 font-medium dark:text-red-400 md:text-6xl">
              Kevin Moreira
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Backend Developer / Front End Developer
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              I have worked for a long time as a freelancer for various
              companies, and now I want to look for a stable job. Here you can
              see everything about me.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/kevin-moreira-3788b1272/">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/Futuredevkev">
                <AiFillGithub />
              </a>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white capitalize">
              technologies
            </h3>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              When I first started programming, I spent about half a year
              focusing on front-end technologies. Today, however, I find myself
              gravitating more towards back-end development.
              <span className="text-red-500"> This </span>
              shift has allowed <span className="text-red-500">me </span>
              to deepen my understanding of the server-side, where I've been
              able to contribute to the core logic and infrastructure that power
              modern applications.
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <span className="icon-[material-symbols--brush] text-6xl text-red-600"></span>
              <h3 className="text-2xl font-medium pt-8 pb-2">Front End</h3>
              <p className="text-gray-800 py-1">React</p>
              <p className="text-gray-800 py-1">Tailwind</p>
              <p className="text-gray-800 py-1">Javascript</p>
              <p className="text-gray-800 py-1">Sass</p>
              <p className="text-gray-800 py-1">Bootstrap</p>
              <p className="text-gray-800 py-1">Typescript</p>
              <p className="text-gray-800 py-1">Next.js</p>
              <p className="text-gray-800 py-1">Vite</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <span className="icon-[mdi--console] text-6xl text-red-600"></span>
              <h3 className="text-2xl font-medium pt-8 pb-2 ">Back End</h3>

              <p className="text-gray-800 py-1">Node.js</p>
              <p className="text-gray-800 py-1">MongoDB</p>
              <p className="text-gray-800 py-1">MySQL</p>
              <p className="text-gray-800 py-1">PostgreSQL</p>
              <p className="text-gray-800 py-1">Nestjs</p>
              <p className="text-gray-800 py-1">Express</p>
              <p className="text-gray-800 py-1">Prisma</p>
              <p className="text-gray-800 py-1">Javascript</p>
            </div>
          </div>
        </section>
        <section className="py-10">
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Portofolio</h3>
          </div>
          <div className="flex flex-col gap-10 py-10 lg:flex-row">
            <div className="basis-1/3 flex-1 ">
              <a href="https://johngelos.com/" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web1}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a href="https://mmfotosuy.com/" target="_blank">
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web2}
                />
              </a>
            </div>
            <div className="basis-1/3 flex-1">
              <a
                href="https://note-happy.vercel.app/notes.html"
                target="_blank"
              >
                <Image
                  className="rounded-lg object-cover"
                  width={"100%"}
                  height={"100%"}
                  layout="responsive"
                  src={web3}
                />
              </a>
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
